# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# This is a fake gamepad create by UTM virtualization on Mac for the touchpad

device_ids: ['0000:0000']
num_buttons: 3
num_axes: 2
deadzone: 0.1
buttons:
  0: '0'
  1: '0'
  2: '0'
  3: '0'
  4: '0'
  5: '0'
  6: '0'
  7: '0'
  8: '0'
  9: '0'
  10: '0'
axes:
  0: '0'
  1: '0'
  2: '0'
  3: '0'
  4: '0'
  5: '0'
  6: '0'
  7: '0'
