# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# C-Tech Callon GP-05 gamepad (used in E-132 lab).

device_ids: ['0810:0001']
num_buttons: 12
num_axes: 6
buttons:
  0: 'b[2]'  # Button 3
  1: 'b[3]'  # Button 4
  2: 'b[1]'  # Button 2
  3: 'b[0]'  # Button 1
  4: 'b[4]'  # LB (top left on back side)
  5: 'b[5]'  # RB (top right on back side)
  6: 'b[8]'  # Select (left in the center)
  7: 'b[9]'  # Start (right in the center)
  8: '0'  # No vendor button
  9: 'b[10]'  # Left joy press
  10: 'b[11]'  # Right joy press
axes:
  0: 'a[0]'  # Left joy left-right (left = 1, right = -1)
  1: 'a[1]'  # Left joy top-down (top = 1, down = -1)
  2: '1-2*b[6]'  # Virtual axis for LT (fully released = 1, fully pressed = -1)
  3: 'a[3]'  # Right joy left-right (left = 1, right = -1); not available in digital mode
  4: 'a[2]'  # Right joy top-down (top = 1, down = -1); not available in digital mode
  5: '1-2*b[7]'  # Virtual axis for RT (fully released = 1, fully pressed = -1)
  6: 'a[4]'  # D-Pad/hat/arrows left-right (left = 1, right = -1); not available in digital mode
  7: 'a[5]'  # D-Pad/hat/arrows top-down (top = 1, down = -1); not available in digital mode