# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

device_ids: ['045e:02a1', '045e:0719']
num_buttons: 15
num_axes: 8
deadzone: 0.25
buttons:
  0: 'b[0]'  # A, green
  1: 'b[1]'  # B, red
  2: 'b[2]'  # X, blue
  3: 'b[3]'  # Y, yellow
  4: 'b[4]'  # LB (top left on back side)
  5: 'b[5]'  # RB (top right on back side)
  6: 'b[6]'  # Back, (left small)
  7: 'b[7]'  # Start, (right small)
  8: 'b[8]'  # XBox button
  9: 'b[9]'  # Left joy press
  10: 'b[10]'  # Right joy press
axes:
  0: 'a[0]'  # Left joy left-right (left = 1, right = -1)
  1: 'a[1]'  # Left joy top-down (top = 1, down = -1)
  2: 'a[2] if vars["lt_initialized"] else 1.0'  # Axis for LT (fully released = 1, fully pressed = -1)
  3: 'a[3]'  # Right joy left-right (left = 1, right = -1)
  4: 'a[4]'  # Right joy top-down (top = 1, down = -1)
  5: 'a[5] if vars["rt_initialized"] else 1.0'  # Axis for RT (fully released = 1, fully pressed = -1)
  6: 'a[6]'  # D-Pad/hat/arrows left-right (left = 1, right = -1)
  7: 'a[7]'  # D-Pad/hat/arrows top-down (top = 1, down = -1)
init:
  trigger_init: "vars['lt_initialized'] = vars['rt_initialized'] = False"
callbacks:
  lt_init: "if a[2] != 0.0:\n\tvars['lt_initialized'] = True"
  rt_init: "if a[5] != 0.0:\n\tvars['rt_initialized'] = True"
